import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ThemeProvider, PartialTheme } from '@fluentui/react/lib/Theme';
import { GetServerSideProps } from 'next'
import { useMemo } from 'react';

const lightTheme: PartialTheme = {
  semanticColors: {
    bodyBackground: 'rgb(107, 123, 192)',
    bodyText: 'white',
  },
};

const Home = ({ data }) => {

  const dataMap = useMemo(() => {
    return data;
  }, [data])

  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.information}>
        <h2>Fake API Company</h2>

        <p style={{ color: "#fff" }}>As Fake API Company, we are happy to give you great service</p>
        <p style={{ backgroundColor: "rgb(107, 123, 192)", color: "#fff", padding: "20px", borderRadius: "10px" }}>Some of Our Employees</p>
      </div>

      <div style={{ margin: "20px", display: "flex", flexWrap: "wrap", justifyContent: "center" }}>
        {
          dataMap.map(item => (
            <ThemeProvider key={item.id} style={{ margin: "20px", padding: "20px", width: "250px", height: "200px", display: "flex", flexDirection: "column", justifyContent: "space-evenly", alignItems: "flex-start" }} theme={lightTheme}>
              <div>Name: {item.name}</div>
              <div>Email: {item.email}</div>
              <div>Phone: {item.phone}</div>
              <div>Website: {item.website}</div>
            </ThemeProvider>
          ))}
      </div>
    </div>
  )
}

export default Home;

type Data = {}


export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data: Data = await res.json();

  return {
    props: {
      data
    }
  }
}